[build]
  command = "cd quotation && npm install --legacy-peer-deps && npm run build"
  publish = "quotation/out"
  functions = "quotation/.netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix"
  NPM_PREFIX = "/opt/buildhome/.npm-global"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

# Handle client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["en"]}

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"